import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "TinyLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-50 text-gray-900">
        <header className="bg-white shadow-md">
          <div className="container mx-auto p-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold text-indigo-600">TinyLink</h1>
          </div>
        </header>
        <main className="container mx-auto grow p-4 sm:p-6 lg:p-8">
          {children}
        </main>
        <footer className="bg-gray-800 text-white p-4 mt-auto">
          <div className="container mx-auto text-center text-sm">
            © {new Date().getFullYear()} TinyLink. Health check:{" "}
            <Link href="/healthz" className="underline">
              /healthz
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
